### ISSUE TITLE
XMLHttpRequest for receiving Server Sent Events (SSE) is only working after browser page is opened

### ISSUE THREAD

**Issue by Aquivion** [binaryminds/react-native-sse#31]
Hello, we are using this library for receiving notifications sent by our webflux stream endpoint on the backend. Our frontend code looks like so:

```
import EventSource from 'react-native-sse'
import 'react-native-url-polyfill/auto'

export const subscribeNotificationEvents = async (accessToken: string) => {
  const url = new URL(`${API_BASE_URL + ':' + NOTIFICATION_SENDER_BE_PORT + ApiEndPoints.NOTIFICATION_EVENTS}`)

  const es = new EventSource(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`
    },
    debug: true
  })

  es.addEventListener('open', (event) => {
    console.log('Open SSE connection.')
  })

  es.addEventListener('message', (event) => {
    console.log('New message event:', event.data)
  })

  es.addEventListener('error', (event) => {
    if (event.type === 'error') {
      console.error('Connection error:', event.message)
    } else if (event.type === 'exception') {
      console.error('Error:', event.message, event.error)
    }
  })

  es.addEventListener('close', (event) => {
    console.log('Close SSE connection.')
  })
}
```

But it is not working. The internal onreadystatechange callback (which should dispatch the message event) is not being called although the SSE's are being sent by the backend. The backend is recognizing the subscriber and also sents the notifications, they are just not being received. Only after some time the onreadystatechange comes back with readyState=4 and status=0

After some trial we figured out that when a browser page is opened in the app **before** the XMLHttpRequest is opened, then the SSE's are suddenly arriving and everything works fine. We use 

```
    import { Linking } from 'react-native'
    Linking.openURL(someURL)
```
to open the browser in-app.

So my question would be: **Does opening a browser in a react native app somehow changes the implementation of the XMLHttpRequest or what is happening here?**

We are using Expo for building the App

**Comment by EmilJunker** [comment]
You need to disable Flipper to make SSE work in React Native on Android. Details here: https://stackoverflow.com/questions/69235694/react-native-cant-connect-to-sse-in-android/69235695#answer-69235695

**Comment by Aquivion** [comment]
Thank you for answering. I tried this solution already but sadly it is not working for me. For me the ReactNativeFlipper file has the following path:

node_modules\react-native\template\android\app\src\debug\java\com\helloworld\ReactNativeFlipper.java

I commented out the suggested lines, but the behaviour stays the same. Maybe that file is not used somehow but it is the only one with that name in our project

**Comment by EmilJunker** [comment]
To confirm whether or not the issue is caused by Flipper, you can run your app in release mode and see if it works. As explained on stackoverflow, the Flipper bug only happens in debug mode. In release mode the SSE should be working.

**Comment by Aquivion** [comment]
@EmilJunker Sorry for delay but I tested it now. The issue is actually resolved by running the project in production mode. However even with commenting out the ReactNativeFlipper module in the node_modules it still won't work in development mode. Could there be another module colliding with this? In any way, thanks for you help!

**Comment by EmilJunker** [comment]
The ReactNativeFlipper file in the node_modules is not the one that causes the issue. There should be a file with this name under `android/app/src/debug/java/com/<projectname>/ReactNativeFlipper.java`. That's the one where you need to comment out the code.

**Comment by Aquivion** [comment]
@EmilJunker Thanks for the answer! My android folder was actually empty, i am using expo and I forgot to run the "npx expo prebuild" command to generate this folder. Now the ReactNativeFlipper.java file is in this location and I commented out the described lines. However I build my project with the "eas build" command and I am not sure if this considers the android folder because it is an online build service. Do you know if I have to build the project locally for it to work? Right now it is still not working

**Comment by EmilJunker** [comment]
Sorry, I have no experience with Expo or online builds. I always build locally.
